version: '3.8'
services:
  app:
    build: .
    container_name: pokeserver
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=${MONGO_URI}
      - NODE_ENV=production
    volumes:
      - .:/app
    command: npm run start