# Use the official Node.js 20 image as the base image
FROM node:20

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install all dependencies (including devDependencies)
RUN npm install

# Install TypeScript, Nodemon, and ts-node globally
RUN npm install -g typescript nodemon ts-node

# Copy the rest of the application code to the working directory
COPY . .

# Expose the application port
EXPOSE 8080

# Command to run the application in development mode
CMD ["npm", "run", "dev"]
